apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sadiqmohamedamine/sadiqfront:v1
        ports:
        - containerPort: 4200
        env:
        - name: BACKEND_URL
          value: http://backend:8080/
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app: frontend
